#!/usr/bin/env tsx
/**
 * LAPI free-backend latency benchmark for DEP's two LLM call sites.
 *
 * Runs two realistic-sized prompts through every free LAPI backend currently
 * registered with the local daemon, prints the measured round-trip latency,
 * and reports whether the response parses as valid JSON matching the schema
 * the production code expects.
 *
 * Free backends only — no API keys needed. Currently:
 *   - mock         (baseline, shows LAPI's own overhead)
 *   - claude-cli   (Claude Pro/Max subscription)
 *   - codex-cli    (ChatGPT Plus/Pro subscription)
 *   - gemini-cli   (Google Code Assist tier; sunsetting 2026-06-18)
 *   - agy-cli      (Antigravity Free tier)
 *
 * Backends that aren't registered with the running daemon are skipped (the
 * /v1/admin/status endpoint is consulted at start).
 *
 * Usage:
 *   npx tsx scripts/lapi-bench.ts
 *
 * Optional env:
 *   LAPI_BASE_URL=http://127.0.0.1:9999   (override daemon URL)
 *   LAPI_TOKEN_PATH=~/.llmbridge/auth.token
 *
 * Output: a markdown-style table to stdout, plus a JSON dump of raw timings
 * at scripts/lapi-bench-results.json for follow-up analysis.
 */

import Anthropic from '@anthropic-ai/sdk'
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  cosineSimilarity,
  embedTexts,
  embeddingsAvailable,
} from '../lib/digital-receptionist/server/embeddings.js'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ─────────────────────────────────────────────────────────────────────────
// LAPI setup
// ─────────────────────────────────────────────────────────────────────────

const LAPI_BASE_URL = process.env.LAPI_BASE_URL ?? 'http://127.0.0.1:9999'
const LAPI_TOKEN_PATH =
  process.env.LAPI_TOKEN_PATH ?? join(homedir(), '.llmbridge', 'auth.token')

function lapiAuthToken(): string {
  if (!existsSync(LAPI_TOKEN_PATH)) {
    throw new Error(
      `LAPI auth token missing at ${LAPI_TOKEN_PATH} — is the daemon running?`,
    )
  }
  return readFileSync(LAPI_TOKEN_PATH, 'utf8').trim()
}

async function lapiAdminStatus(): Promise<{ projects: Array<{ name: string; backend: string }> }> {
  const token = lapiAuthToken()
  const res = await fetch(`${LAPI_BASE_URL}/v1/admin/status`, {
    headers: { Authorization: `Bearer ${token}` },
  })
  if (!res.ok) {
    throw new Error(`LAPI /v1/admin/status returned ${res.status}`)
  }
  return res.json() as Promise<{ projects: Array<{ name: string; backend: string }> }>
}

/**
 * Probe `/v1/tools?backend=<id>` to confirm a backend is registered with the
 * daemon. Returns true on 200, false on 404. Used to skip backends gracefully.
 */
async function backendIsRegistered(backendId: string): Promise<boolean> {
  const token = lapiAuthToken()
  const res = await fetch(
    `${LAPI_BASE_URL}/v1/tools?backend=${encodeURIComponent(backendId)}`,
    { headers: { Authorization: `Bearer ${token}` } },
  )
  return res.status === 200
}

// ─────────────────────────────────────────────────────────────────────────
// Project YAMLs — one per backend we want to bench
// ─────────────────────────────────────────────────────────────────────────

const PROJECTS_DIR = join(homedir(), '.llmbridge', 'projects')

const BENCH_BACKENDS = [
  'mock',
  'claude-cli',
  'codex-cli',
  'gemini-cli',
  'agy-cli',
] as const
type BenchBackend = (typeof BENCH_BACKENDS)[number]

function ensureProjectYaml(backend: BenchBackend): string {
  const projectName = `bench-${backend}`
  const path = join(PROJECTS_DIR, `${projectName}.yaml`)
  if (existsSync(path)) return projectName
  mkdirSync(PROJECTS_DIR, { recursive: true })
  const yaml = `# Auto-generated by DEP/scripts/lapi-bench.ts
name: ${projectName}
backend: ${backend}
tools:
  read: false
  write: false
  shell: false
  web: false
`
  writeFileSync(path, yaml, 'utf8')
  console.log(`  wrote ${path}`)
  return projectName
}

// ─────────────────────────────────────────────────────────────────────────
// Realistic DEP-shaped prompts
// ─────────────────────────────────────────────────────────────────────────

type CatalogEntry = { id: string; canonical: string; answer: string }

/**
 * Synthesize a 50-entry catalog roughly matching what an APC kiosk's
 * approved-answer list looks like. Mixed AR/FR/EN topics, ~150 tokens each.
 * The actual content doesn't matter for benchmarking; what matters is the
 * prompt size matches what DEP's llm-match.ts produces in production.
 */
function buildCatalog(): CatalogEntry[] {
  const topics = [
    'opening hours',
    'id card renewal',
    'passport application',
    'birth certificate request',
    'driver license renewal',
    'civil status documents',
    'family record book',
    'address change registration',
    'lost id replacement',
    'minor passport with parental consent',
  ]
  const catalog: CatalogEntry[] = []
  for (let i = 0; i < 50; i += 1) {
    const topic = topics[i % topics.length]
    catalog.push({
      id: `entry-${String(i + 1).padStart(2, '0')}`,
      canonical: `Combien de temps pour ${topic}? / كم من الوقت يستغرق ${topic}؟ / How long does ${topic} take?`,
      answer:
        `Pour ${topic}, comptez généralement 5 à 10 jours ouvrables. ` +
        `بالنسبة لـ ${topic}، الوقت المعتاد هو 5 إلى 10 أيام عمل. ` +
        `For ${topic}, the typical turnaround is 5 to 10 working days. ` +
        `Apportez la pièce justificative principale et un justificatif de domicile récent. ` +
        `Bring your primary supporting document and a recent proof of residence.`,
    })
  }
  return catalog
}

const MATCHER_SYSTEM_PROMPT = [
  'You match a visitor question against a catalog of approved answers for an office reception assistant.',
  '',
  'Rules:',
  '1. Return the id of the catalog entry that BEST answers the visitor\'s question.',
  '2. Match on meaning, not on exact words.',
  '3. If NO approved answer truly answers the question, return matchedAnswerId=null. Do NOT guess.',
  '4. Set confidence to "high" / "medium" / "low".',
  '',
  'Output strict JSON matching the schema.',
].join('\n')

const MATCHER_SCHEMA = {
  type: 'object',
  properties: {
    matchedAnswerId: { type: ['string', 'null'] },
    confidence: { type: 'string', enum: ['high', 'medium', 'low'] },
  },
  required: ['matchedAnswerId', 'confidence'],
  additionalProperties: false,
} as const

function buildMatcherUserMessage(catalog: CatalogEntry[]): string {
  const list = catalog
    .map((e, i) => `${i + 1}. id="${e.id}"\n   Q: ${e.canonical}\n   A: ${e.answer}`)
    .join('\n')
  return (
    `Approved answers (language: fr):\n${list}\n\n` +
    `Visitor question (language: fr): "Combien de temps pour faire renouveler ma carte d'identité ?"\n\n` +
    'Return the matching id (or null) per the schema.'
  )
}

const DRAFTER_SYSTEM_PROMPT = [
  'You draft suggested answers for a digital reception assistant in a public-service office.',
  'Office: APC d\'Hydra — Mairie d\'Hydra, Alger.',
  'Service summary: État civil, cartes d\'identité, démarches administratives.',
  'Opening hours: 8h-15h30 du dimanche au jeudi.',
  '',
  'Rules:',
  '1. Produce a short, factual draft answer (2–4 sentences) in Arabic, French, and English.',
  '2. Stay within the scope of what this office actually handles.',
  '3. Never invent specific document numbers, prices, or counter numbers.',
  '4. Keep the tone direct and helpful, suitable to be read aloud.',
  '5. Output JSON only, matching the schema exactly.',
].join('\n')

const DRAFTER_SCHEMA = {
  type: 'object',
  properties: {
    ar: { type: 'string' },
    fr: { type: 'string' },
    en: { type: 'string' },
  },
  required: ['ar', 'fr', 'en'],
  additionalProperties: false,
} as const

const DRAFTER_USER_MESSAGE =
  'Visitor question (language: fr):\n' +
  'Est-ce que je peux récupérer mon extrait de naissance pour mon fils mineur sans qu\'il soit présent ?\n\n' +
  'Return a draft answer in all three languages following the schema.'

// ─────────────────────────────────────────────────────────────────────────
// Bench runner
// ─────────────────────────────────────────────────────────────────────────

type Outcome = {
  backend: BenchBackend
  prompt: 'matcher' | 'matcher-prefilter' | 'drafter'
  ok: boolean
  ms: number
  parseOk: boolean
  parseError?: string
  text: string
  errorMessage?: string
}

const PRE_FILTER_TOP_K = 8

async function callLapi(opts: {
  projectName: string
  backend: BenchBackend
  system: string
  schema: Record<string, unknown>
  userMessage: string
}): Promise<{ text: string; ms: number; errorMessage?: string }> {
  const client = new Anthropic({
    baseURL: LAPI_BASE_URL,
    authToken: lapiAuthToken(),
    defaultHeaders: { 'X-Project': opts.projectName },
    // Disable SDK retries — we want one round-trip, one timing.
    maxRetries: 0,
  })

  const start = Date.now()
  try {
    const response = await client.messages.create({
      model: opts.backend, // LAPI uses backend id, not provider model id
      max_tokens: 1024,
      system: opts.system,
      output_config: { format: { type: 'json_schema', schema: opts.schema } },
      messages: [{ role: 'user', content: opts.userMessage }],
    })
    const ms = Date.now() - start
    const textBlock = response.content.find((b) => b.type === 'text')
    const text =
      textBlock && textBlock.type === 'text' && typeof textBlock.text === 'string'
        ? textBlock.text
        : ''
    return { text, ms }
  } catch (error) {
    const ms = Date.now() - start
    return {
      text: '',
      ms,
      errorMessage: error instanceof Error ? error.message : String(error),
    }
  }
}

function tryParse(text: string, schema: 'matcher' | 'drafter'): { ok: boolean; err?: string } {
  if (!text) return { ok: false, err: 'empty response' }
  // CLI backends commonly wrap JSON in prose/markdown. Try to recover the
  // first `{...}` block before failing.
  const candidate = text.trim()
  const direct = (() => {
    try {
      return JSON.parse(candidate)
    } catch {
      return undefined
    }
  })()
  const parsed: unknown =
    direct ??
    (() => {
      const m = candidate.match(/\{[\s\S]*\}/)
      if (!m) return undefined
      try {
        return JSON.parse(m[0])
      } catch {
        return undefined
      }
    })()

  if (!parsed || typeof parsed !== 'object') {
    return { ok: false, err: 'no JSON object found in response' }
  }
  const obj = parsed as Record<string, unknown>
  if (schema === 'matcher') {
    if (
      !('matchedAnswerId' in obj) ||
      !('confidence' in obj) ||
      !['high', 'medium', 'low'].includes(obj.confidence as string)
    ) {
      return { ok: false, err: 'missing matchedAnswerId/confidence fields' }
    }
    return { ok: true }
  }
  if (
    typeof obj.ar !== 'string' ||
    typeof obj.fr !== 'string' ||
    typeof obj.en !== 'string'
  ) {
    return { ok: false, err: 'missing ar/fr/en string fields' }
  }
  return { ok: true }
}

async function preFilterTopK(
  question: string,
  catalog: CatalogEntry[],
  k: number,
): Promise<CatalogEntry[]> {
  const catalogTexts = catalog.map((c) => c.canonical)
  const catalogVectors = await embedTexts(catalogTexts)
  const [questionVector] = await embedTexts([question])
  const scored = catalog.map((c, i) => ({
    candidate: c,
    score: cosineSimilarity(questionVector, catalogVectors[i]),
  }))
  scored.sort((a, b) => b.score - a.score)
  return scored.slice(0, k).map((s) => s.candidate)
}

async function benchOne(
  backend: BenchBackend,
  catalog: CatalogEntry[],
  preFilteredCatalog: CatalogEntry[] | null,
): Promise<Outcome[]> {
  const projectName = ensureProjectYaml(backend)
  const outcomes: Outcome[] = []

  // Matcher (full catalog, baseline — what production was doing pre-embedding)
  process.stdout.write(`  ${backend} / matcher (full ${catalog.length})  ... `)
  const m = await callLapi({
    projectName,
    backend,
    system: MATCHER_SYSTEM_PROMPT,
    schema: MATCHER_SCHEMA,
    userMessage: buildMatcherUserMessage(catalog),
  })
  const mParse = tryParse(m.text, 'matcher')
  console.log(
    `${(m.ms / 1000).toFixed(2)}s ${m.errorMessage ? `(ERR: ${m.errorMessage.slice(0, 60)})` : mParse.ok ? '(parse ok)' : `(parse FAIL: ${mParse.err})`}`,
  )
  outcomes.push({
    backend,
    prompt: 'matcher',
    ok: !m.errorMessage,
    ms: m.ms,
    parseOk: mParse.ok,
    parseError: mParse.err,
    text: m.text,
    errorMessage: m.errorMessage,
  })

  // Matcher (two-stage: embedding pre-filter narrows to top-K, LLM tie-breaks)
  if (preFilteredCatalog) {
    process.stdout.write(
      `  ${backend} / matcher (pre-filter top-${preFilteredCatalog.length})  ... `,
    )
    const mp = await callLapi({
      projectName,
      backend,
      system: MATCHER_SYSTEM_PROMPT,
      schema: MATCHER_SCHEMA,
      userMessage: buildMatcherUserMessage(preFilteredCatalog),
    })
    const mpParse = tryParse(mp.text, 'matcher')
    console.log(
      `${(mp.ms / 1000).toFixed(2)}s ${mp.errorMessage ? `(ERR: ${mp.errorMessage.slice(0, 60)})` : mpParse.ok ? '(parse ok)' : `(parse FAIL: ${mpParse.err})`}`,
    )
    outcomes.push({
      backend,
      prompt: 'matcher-prefilter',
      ok: !mp.errorMessage,
      ms: mp.ms,
      parseOk: mpParse.ok,
      parseError: mpParse.err,
      text: mp.text,
      errorMessage: mp.errorMessage,
    })
  }

  // Drafter
  process.stdout.write(`  ${backend} / drafter  ... `)
  const d = await callLapi({
    projectName,
    backend,
    system: DRAFTER_SYSTEM_PROMPT,
    schema: DRAFTER_SCHEMA,
    userMessage: DRAFTER_USER_MESSAGE,
  })
  const dParse = tryParse(d.text, 'drafter')
  console.log(
    `${(d.ms / 1000).toFixed(2)}s ${d.errorMessage ? `(ERR: ${d.errorMessage.slice(0, 60)})` : dParse.ok ? '(parse ok)' : `(parse FAIL: ${dParse.err})`}`,
  )
  outcomes.push({
    backend,
    prompt: 'drafter',
    ok: !d.errorMessage,
    ms: d.ms,
    parseOk: dParse.ok,
    parseError: dParse.err,
    text: d.text,
    errorMessage: d.errorMessage,
  })

  return outcomes
}

function printTable(results: Outcome[], hasPreFilter: boolean): void {
  type Row = { matcher?: Outcome; 'matcher-prefilter'?: Outcome; drafter?: Outcome }
  const grouped = new Map<BenchBackend, Row>()
  for (const r of results) {
    if (!grouped.has(r.backend)) grouped.set(r.backend, {})
    grouped.get(r.backend)![r.prompt] = r
  }

  const fmt = (o?: Outcome) =>
    o ? (o.errorMessage ? `ERR ${(o.ms / 1000).toFixed(1)}s` : `${(o.ms / 1000).toFixed(2)}s`) : '—'
  const parseStr = (o?: Outcome) =>
    o ? (o.errorMessage ? '—' : o.parseOk ? '✓' : '✗') : '—'

  console.log('')
  console.log('### Measured latencies (real DEP-shaped prompts via LAPI)')
  console.log('')

  if (hasPreFilter) {
    console.log(
      '| Backend     | Matcher (full 50)     | Matcher (pre-filter top-8) | Speedup | Drafter (trilingual) | Match-full JSON | Match-pf JSON | Drafter JSON |',
    )
    console.log(
      '|-------------|-----------------------|----------------------------|---------|----------------------|-----------------|---------------|--------------|',
    )
    for (const backend of BENCH_BACKENDS) {
      const row = grouped.get(backend)
      if (!row) {
        console.log(`| \`${backend.padEnd(11)}\` | not registered        | not registered             | —       | not registered       | —               | —             | —            |`)
        continue
      }
      const speedup =
        row.matcher && row['matcher-prefilter'] && !row.matcher.errorMessage && !row['matcher-prefilter'].errorMessage
          ? `${(row.matcher.ms / row['matcher-prefilter'].ms).toFixed(1)}×`
          : '—'
      console.log(
        `| \`${backend.padEnd(11)}\` | ${fmt(row.matcher).padEnd(21)} | ${fmt(row['matcher-prefilter']).padEnd(26)} | ${speedup.padEnd(7)} | ${fmt(row.drafter).padEnd(20)} | ${parseStr(row.matcher).padEnd(15)} | ${parseStr(row['matcher-prefilter']).padEnd(13)} | ${parseStr(row.drafter).padEnd(12)} |`,
      )
    }
  } else {
    console.log('| Backend     | Matcher (~7.5k input) | Drafter (trilingual) | Matcher JSON | Drafter JSON |')
    console.log('|-------------|-----------------------|----------------------|--------------|--------------|')
    for (const backend of BENCH_BACKENDS) {
      const row = grouped.get(backend)
      if (!row) {
        console.log(`| \`${backend}\` | not registered        | not registered       | —            | —            |`)
        continue
      }
      console.log(
        `| \`${backend.padEnd(11)}\` | ${fmt(row.matcher).padEnd(21)} | ${fmt(row.drafter).padEnd(20)} | ${parseStr(row.matcher).padEnd(12)} | ${parseStr(row.drafter).padEnd(12)} |`,
      )
    }
  }
  console.log('')
  console.log('Legend: ✓ = response parsed as the expected JSON schema, ✗ = parse failed (model returned prose / malformed JSON).')
  if (hasPreFilter) {
    console.log('Pre-filter: embedded the catalog locally (sentence-transformers, no network) and sent only the top-8 most-similar entries to the LLM. Embedding overhead is included in the timing.')
  }
}

async function main(): Promise<void> {
  console.log('LAPI free-backend bench for DEP\n')
  console.log(`  base URL : ${LAPI_BASE_URL}`)
  console.log(`  token at : ${LAPI_TOKEN_PATH}`)

  // Verify daemon reachable
  try {
    await lapiAdminStatus()
  } catch (err) {
    console.error(
      `\nFATAL: cannot reach LAPI at ${LAPI_BASE_URL}: ${err instanceof Error ? err.message : err}`,
    )
    console.error('Start the daemon with: cd /Volumes/My\\ Book\\ Duo-1/Dev/LAPI && npx tsx src/cli.ts start')
    process.exit(1)
  }

  console.log('  daemon   : reachable ✓\n')

  // Probe which backends are registered
  console.log('Probing registered backends:')
  const registered: BenchBackend[] = []
  for (const b of BENCH_BACKENDS) {
    const ok = await backendIsRegistered(b)
    console.log(`  ${b}${' '.repeat(12 - b.length)} ${ok ? '✓ registered' : '— not registered, will skip'}`)
    if (ok) registered.push(b)
  }
  console.log('')

  if (registered.length === 0) {
    console.error('No free backends registered. Nothing to bench.')
    process.exit(1)
  }

  // Pre-compute the embedding pre-filter once, BEFORE timing the LLM calls.
  // We bake the embedding cost into the matcher-prefilter timing per backend,
  // so this top-level call just primes the worker + warms the model.
  const catalog = buildCatalog()
  let preFilteredCatalog: CatalogEntry[] | null = null
  if (embeddingsAvailable()) {
    console.log('Local embeddings worker available — will measure two-stage matcher too.')
    process.stdout.write('Warming embeddings worker + pre-filtering catalog (one-time) ... ')
    const tWarm = Date.now()
    const visitorQuestion =
      "Combien de temps pour faire renouveler ma carte d'identité ?"
    try {
      preFilteredCatalog = await (async () => {
        const catalogTexts = catalog.map((c) => c.canonical)
        const catalogVectors = await embedTexts(catalogTexts)
        const [questionVector] = await embedTexts([visitorQuestion])
        const scored = catalog.map((c, i) => ({
          c,
          s: cosineSimilarity(questionVector, catalogVectors[i]),
        }))
        scored.sort((a, b) => b.s - a.s)
        console.log(`${((Date.now() - tWarm) / 1000).toFixed(2)}s (embedded ${catalog.length} + 1 question)`)
        console.log(
          `  Top-${PRE_FILTER_TOP_K} by cosine similarity: ${scored
            .slice(0, PRE_FILTER_TOP_K)
            .map((x) => `${x.c.id}(${x.s.toFixed(2)})`)
            .join(', ')}`,
        )
        return scored.slice(0, PRE_FILTER_TOP_K).map((x) => x.c)
      })()
    } catch (err) {
      console.log(`FAILED: ${err instanceof Error ? err.message : err}`)
      console.log('  → continuing without pre-filter measurement')
      preFilteredCatalog = null
    }
  } else {
    console.log('EMBEDDINGS_WORKER_COMMAND unset — will measure only the full-catalog matcher.')
  }

  console.log('')
  console.log('Running benchmark (each backend × matcher full × matcher pre-filter × drafter):\n')
  const allResults: Outcome[] = []

  for (const backend of registered) {
    const outcomes = await benchOne(backend, catalog, preFilteredCatalog)
    allResults.push(...outcomes)
  }

  printTable(allResults, preFilteredCatalog !== null)

  // Persist raw results
  const outPath = resolve(__dirname, 'lapi-bench-results.json')
  writeFileSync(
    outPath,
    JSON.stringify(
      {
        timestamp: new Date().toISOString(),
        baseUrl: LAPI_BASE_URL,
        results: allResults,
      },
      null,
      2,
    ),
  )
  console.log(`Raw results: ${outPath}`)
}

main().catch((err) => {
  console.error('bench failed:', err)
  process.exit(1)
})
