#!/usr/bin/env tsx
/**
 * LAPI free-backend latency benchmark for DEP's two LLM call sites.
 *
 * Runs two realistic-sized prompts through every free LAPI backend currently
 * registered with the local daemon, prints the measured round-trip latency,
 * and reports whether the response parses as valid JSON matching the schema
 * the production code expects.
 *
 * Free backends only — no API keys needed. Currently:
 *   - mock         (baseline, shows LAPI's own overhead)
 *   - claude-cli   (Claude Pro/Max subscription)
 *   - codex-cli    (ChatGPT Plus/Pro subscription)
 *   - gemini-cli   (Google Code Assist tier; sunsetting 2026-06-18)
 *   - agy-cli      (Antigravity Free tier)
 *
 * Backends that aren't registered with the running daemon are skipped (the
 * /v1/admin/status endpoint is consulted at start).
 *
 * Usage:
 *   npx tsx scripts/lapi-bench.ts
 *
 * Optional env:
 *   LAPI_BASE_URL=http://127.0.0.1:9999   (override daemon URL)
 *   LAPI_TOKEN_PATH=~/.llmbridge/auth.token
 *
 * Output: a markdown-style table to stdout, plus a JSON dump of raw timings
 * at scripts/lapi-bench-results.json for follow-up analysis.
 */

import Anthropic from '@anthropic-ai/sdk'
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  cosineSimilarity,
  embedTexts,
  embeddingsAvailable,
} from '../lib/digital-receptionist/server/embeddings.js'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ─────────────────────────────────────────────────────────────────────────
// LAPI setup
// ─────────────────────────────────────────────────────────────────────────

const LAPI_BASE_URL = process.env.LAPI_BASE_URL ?? 'http://127.0.0.1:9999'
const LAPI_TOKEN_PATH =
  process.env.LAPI_TOKEN_PATH ?? join(homedir(), '.llmbridge', 'auth.token')

function lapiAuthToken(): string {
  if (!existsSync(LAPI_TOKEN_PATH)) {
    throw new Error(
      `LAPI auth token missing at ${LAPI_TOKEN_PATH} — is the daemon running?`,
    )
  }
  return readFileSync(LAPI_TOKEN_PATH, 'utf8').trim()
}

async function lapiAdminStatus(): Promise<{ projects: Array<{ name: string; backend: string }> }> {
  const token = lapiAuthToken()
  const res = await fetch(`${LAPI_BASE_URL}/v1/admin/status`, {
    headers: { Authorization: `Bearer ${token}` },
  })
  if (!res.ok) {
    throw new Error(`LAPI /v1/admin/status returned ${res.status}`)
  }
  return res.json() as Promise<{ projects: Array<{ name: string; backend: string }> }>
}

/**
 * Probe `/v1/tools?backend=<id>` to confirm a backend is registered with the
 * daemon. Returns true on 200, false on 404. Used to skip backends gracefully.
 */
async function backendIsRegistered(backendId: string): Promise<boolean> {
  const token = lapiAuthToken()
  const res = await fetch(
    `${LAPI_BASE_URL}/v1/tools?backend=${encodeURIComponent(backendId)}`,
    { headers: { Authorization: `Bearer ${token}` } },
  )
  return res.status === 200
}

// ─────────────────────────────────────────────────────────────────────────
// Project YAMLs — one per backend we want to bench
// ─────────────────────────────────────────────────────────────────────────

const PROJECTS_DIR = join(homedir(), '.llmbridge', 'projects')

const BENCH_BACKENDS = [
  'mock',
  'claude-cli',
  'codex-cli',
  'gemini-cli',
  'agy-cli',
] as const
type BenchBackend = (typeof BENCH_BACKENDS)[number]

function ensureProjectYaml(backend: BenchBackend): string {
  const projectName = `bench-${backend}`
  const path = join(PROJECTS_DIR, `${projectName}.yaml`)
  if (existsSync(path)) return projectName
  mkdirSync(PROJECTS_DIR, { recursive: true })
  const yaml = `# Auto-generated by DEP/scripts/lapi-bench.ts
name: ${projectName}
backend: ${backend}
tools:
  read: false
  write: false
  shell: false
  web: false
`
  writeFileSync(path, yaml, 'utf8')
  console.log(`  wrote ${path}`)
  return projectName
}

// ─────────────────────────────────────────────────────────────────────────
// Realistic DEP-shaped prompts
// ─────────────────────────────────────────────────────────────────────────

type CatalogEntry = { id: string; canonical: string; answer: string }

/**
 * Synthesize a 50-entry catalog roughly matching what an APC kiosk's
 * approved-answer list looks like. Mixed AR/FR/EN topics, ~150 tokens each.
 * The actual content doesn't matter for benchmarking; what matters is the
 * prompt size matches what DEP's llm-match.ts produces in production.
 */
function buildCatalog(): CatalogEntry[] {
  const topics = [
    'opening hours',
    'id card renewal',
    'passport application',
    'birth certificate request',
    'driver license renewal',
    'civil status documents',
    'family record book',
    'address change registration',
    'lost id replacement',
    'minor passport with parental consent',
  ]
  const catalog: CatalogEntry[] = []
  for (let i = 0; i < 50; i += 1) {
    const topic = topics[i % topics.length]
    catalog.push({
      id: `entry-${String(i + 1).padStart(2, '0')}`,
      canonical: `Combien de temps pour ${topic}? / كم من الوقت يستغرق ${topic}؟ / How long does ${topic} take?`,
      answer:
        `Pour ${topic}, comptez généralement 5 à 10 jours ouvrables. ` +
        `بالنسبة لـ ${topic}، الوقت المعتاد هو 5 إلى 10 أيام عمل. ` +
        `For ${topic}, the typical turnaround is 5 to 10 working days. ` +
        `Apportez la pièce justificative principale et un justificatif de domicile récent. ` +
        `Bring your primary supporting document and a recent proof of residence.`,
    })
  }
  return catalog
}

const MATCHER_SYSTEM_PROMPT = [
  'You match a visitor question against a catalog of approved answers for an office reception assistant.',
  '',
  'Rules:',
  '1. Return the id of the catalog entry that BEST answers the visitor\'s question.',
  '2. Match on meaning, not on exact words.',
  '3. If NO approved answer truly answers the question, return matchedAnswerId=null. Do NOT guess.',
  '4. Set confidence to "high" / "medium" / "low".',
  '',
  'Output strict JSON matching the schema.',
].join('\n')

const MATCHER_SCHEMA = {
  type: 'object',
  properties: {
    matchedAnswerId: { type: ['string', 'null'] },
    confidence: { type: 'string', enum: ['high', 'medium', 'low'] },
  },
  required: ['matchedAnswerId', 'confidence'],
  additionalProperties: false,
} as const

function buildMatcherUserMessage(catalog: CatalogEntry[]): string {
  const list = catalog
    .map((e, i) => `${i + 1}. id="${e.id}"\n   Q: ${e.canonical}\n   A: ${e.answer}`)
    .join('\n')
  return (
    `Approved answers (language: fr):\n${list}\n\n` +
    `Visitor question (language: fr): "Combien de temps pour faire renouveler ma carte d'identité ?"\n\n` +
    'Return the matching id (or null) per the schema.'
  )
}

const DRAFTER_SYSTEM_PROMPT = [
  'You draft suggested answers for a digital reception assistant in a public-service office.',
  'Office: APC d\'Hydra — Mairie d\'Hydra, Alger.',
  'Service summary: État civil, cartes d\'identité, démarches administratives.',
  'Opening hours: 8h-15h30 du dimanche au jeudi.',
  '',
  'Rules:',
  '1. Produce a short, factual draft answer (2–4 sentences) in Arabic, French, and English.',
  '2. Stay within the scope of what this office actually handles.',
  '3. Never invent specific document numbers, prices, or counter numbers.',
  '4. Keep the tone direct and helpful, suitable to be read aloud.',
  '5. Output JSON only, matching the schema exactly.',
].join('\n')

const DRAFTER_SCHEMA = {
  type: 'object',
  properties: {
    ar: { type: 'string' },
    fr: { type: 'string' },
    en: { type: 'string' },
  },
  required: ['ar', 'fr', 'en'],
  additionalProperties: false,
} as const

const DRAFTER_USER_MESSAGE =
  'Visitor question (language: fr):\n' +
  'Est-ce que je peux récupérer mon extrait de naissance pour mon fils mineur sans qu\'il soit présent ?\n\n' +
  'Return a draft answer in all three languages following the schema.'

// ─────────────────────────────────────────────────────────────────────────
// Bench runner
// ─────────────────────────────────────────────────────────────────────────

type PromptKind = 'matcher' | 'matcher-prefilter' | 'drafter'

type Sample = {
  ms: number
  parseOk: boolean
  parseError?: string
  errorMessage?: string
  text: string
}

type Outcome = {
  backend: BenchBackend
  prompt: PromptKind
  samples: Sample[]
}

const PRE_FILTER_TOP_K = 8

// How many samples per (backend, prompt) — see scripts/lapi-bench.ts header
// for the rationale. First sample is dropped as warm-up (lets the OS file
// cache and any DNS / TLS handshakes settle), the remaining N-1 are
// reported as median + p95 + min + max.
const SAMPLES_PER_CELL = 10
const MOCK_SAMPLES = 3 // mock is just baseline; thrashing it doesn't tell us anything

function statsOf(samplesMs: number[]): { median: number; p95: number; min: number; max: number } {
  const sorted = [...samplesMs].sort((a, b) => a - b)
  const median = sorted[Math.floor(sorted.length / 2)]
  const p95idx = Math.min(sorted.length - 1, Math.ceil(sorted.length * 0.95) - 1)
  const p95 = sorted[p95idx]
  return { median, p95, min: sorted[0], max: sorted[sorted.length - 1] }
}

async function callLapi(opts: {
  projectName: string
  backend: BenchBackend
  system: string
  schema: Record<string, unknown>
  userMessage: string
}): Promise<{ text: string; ms: number; errorMessage?: string }> {
  const client = new Anthropic({
    baseURL: LAPI_BASE_URL,
    authToken: lapiAuthToken(),
    defaultHeaders: { 'X-Project': opts.projectName },
    // Disable SDK retries — we want one round-trip, one timing.
    maxRetries: 0,
  })

  const start = Date.now()
  try {
    const response = await client.messages.create({
      model: opts.backend, // LAPI uses backend id, not provider model id
      max_tokens: 1024,
      system: opts.system,
      output_config: { format: { type: 'json_schema', schema: opts.schema } },
      messages: [{ role: 'user', content: opts.userMessage }],
    })
    const ms = Date.now() - start
    const textBlock = response.content.find((b) => b.type === 'text')
    const text =
      textBlock && textBlock.type === 'text' && typeof textBlock.text === 'string'
        ? textBlock.text
        : ''
    return { text, ms }
  } catch (error) {
    const ms = Date.now() - start
    return {
      text: '',
      ms,
      errorMessage: error instanceof Error ? error.message : String(error),
    }
  }
}

function tryParse(text: string, schema: 'matcher' | 'drafter'): { ok: boolean; err?: string } {
  if (!text) return { ok: false, err: 'empty response' }
  // CLI backends commonly wrap JSON in prose/markdown. Try to recover the
  // first `{...}` block before failing.
  const candidate = text.trim()
  const direct = (() => {
    try {
      return JSON.parse(candidate)
    } catch {
      return undefined
    }
  })()
  const parsed: unknown =
    direct ??
    (() => {
      const m = candidate.match(/\{[\s\S]*\}/)
      if (!m) return undefined
      try {
        return JSON.parse(m[0])
      } catch {
        return undefined
      }
    })()

  if (!parsed || typeof parsed !== 'object') {
    return { ok: false, err: 'no JSON object found in response' }
  }
  const obj = parsed as Record<string, unknown>
  if (schema === 'matcher') {
    if (
      !('matchedAnswerId' in obj) ||
      !('confidence' in obj) ||
      !['high', 'medium', 'low'].includes(obj.confidence as string)
    ) {
      return { ok: false, err: 'missing matchedAnswerId/confidence fields' }
    }
    return { ok: true }
  }
  if (
    typeof obj.ar !== 'string' ||
    typeof obj.fr !== 'string' ||
    typeof obj.en !== 'string'
  ) {
    return { ok: false, err: 'missing ar/fr/en string fields' }
  }
  return { ok: true }
}

async function preFilterTopK(
  question: string,
  catalog: CatalogEntry[],
  k: number,
): Promise<CatalogEntry[]> {
  const catalogTexts = catalog.map((c) => c.canonical)
  const catalogVectors = await embedTexts(catalogTexts)
  const [questionVector] = await embedTexts([question])
  const scored = catalog.map((c, i) => ({
    candidate: c,
    score: cosineSimilarity(questionVector, catalogVectors[i]),
  }))
  scored.sort((a, b) => b.score - a.score)
  return scored.slice(0, k).map((s) => s.candidate)
}

async function runOneSample(opts: {
  projectName: string
  backend: BenchBackend
  system: string
  schema: Record<string, unknown>
  userMessage: string
  parseAs: 'matcher' | 'drafter'
}): Promise<Sample> {
  const r = await callLapi({
    projectName: opts.projectName,
    backend: opts.backend,
    system: opts.system,
    schema: opts.schema,
    userMessage: opts.userMessage,
  })
  const parsed = tryParse(r.text, opts.parseAs)
  return {
    ms: r.ms,
    parseOk: parsed.ok,
    parseError: parsed.err,
    errorMessage: r.errorMessage,
    text: r.text,
  }
}

async function benchMultiSample(opts: {
  backend: BenchBackend
  prompt: PromptKind
  projectName: string
  system: string
  schema: Record<string, unknown>
  userMessage: string
  parseAs: 'matcher' | 'drafter'
  samples: number
  label: string
}): Promise<Outcome> {
  const collected: Sample[] = []
  process.stdout.write(`  ${opts.backend} / ${opts.label} (${opts.samples} samples)`)
  for (let i = 0; i < opts.samples; i += 1) {
    const s = await runOneSample({
      projectName: opts.projectName,
      backend: opts.backend,
      system: opts.system,
      schema: opts.schema,
      userMessage: opts.userMessage,
      parseAs: opts.parseAs,
    })
    collected.push(s)
    const marker = s.errorMessage ? 'E' : s.parseOk ? '.' : '!'
    process.stdout.write(marker)
  }
  // Summary
  const successes = collected.filter((s) => !s.errorMessage).map((s) => s.ms)
  const sample1ms = collected[0]?.ms ?? 0
  const lastMs = collected[collected.length - 1]?.ms ?? 0
  if (successes.length === 0) {
    process.stdout.write(`  ALL FAILED\n`)
  } else {
    // Drop the first sample (warm-up) from stats.
    const measured = collected.length > 1 ? successes.slice(1) : successes
    const s = statsOf(measured)
    const parsePass = collected.filter((c) => c.parseOk).length
    const warmupDelta = collected.length > 1
      ? `(s1=${(sample1ms / 1000).toFixed(1)}s, last=${(lastMs / 1000).toFixed(1)}s)`
      : ''
    process.stdout.write(
      `  median=${(s.median / 1000).toFixed(2)}s p95=${(s.p95 / 1000).toFixed(2)}s min=${(s.min / 1000).toFixed(2)}s max=${(s.max / 1000).toFixed(2)}s  parse-ok=${parsePass}/${collected.length} ${warmupDelta}\n`,
    )
  }
  return {
    backend: opts.backend,
    prompt: opts.prompt,
    samples: collected,
  }
}

async function benchOne(
  backend: BenchBackend,
  catalog: CatalogEntry[],
  preFilteredCatalog: CatalogEntry[] | null,
): Promise<Outcome[]> {
  const projectName = ensureProjectYaml(backend)
  const outcomes: Outcome[] = []
  const samples = backend === 'mock' ? MOCK_SAMPLES : SAMPLES_PER_CELL

  // Matcher (full catalog, baseline — what production was doing pre-embedding)
  outcomes.push(
    await benchMultiSample({
      backend,
      prompt: 'matcher',
      projectName,
      system: MATCHER_SYSTEM_PROMPT,
      schema: MATCHER_SCHEMA,
      userMessage: buildMatcherUserMessage(catalog),
      parseAs: 'matcher',
      samples,
      label: `matcher (full ${catalog.length})`,
    }),
  )

  // Matcher (two-stage: embedding pre-filter narrows to top-K)
  if (preFilteredCatalog) {
    outcomes.push(
      await benchMultiSample({
        backend,
        prompt: 'matcher-prefilter',
        projectName,
        system: MATCHER_SYSTEM_PROMPT,
        schema: MATCHER_SCHEMA,
        userMessage: buildMatcherUserMessage(preFilteredCatalog),
        parseAs: 'matcher',
        samples,
        label: `matcher (pre-filter top-${preFilteredCatalog.length})`,
      }),
    )
  }

  // Drafter — fewer samples since each call is heavier (~10-30s)
  const drafterSamples = backend === 'mock' ? MOCK_SAMPLES : Math.min(samples, 5)
  outcomes.push(
    await benchMultiSample({
      backend,
      prompt: 'drafter',
      projectName,
      system: DRAFTER_SYSTEM_PROMPT,
      schema: DRAFTER_SCHEMA,
      userMessage: DRAFTER_USER_MESSAGE,
      parseAs: 'drafter',
      samples: drafterSamples,
      label: 'drafter',
    }),
  )

  return outcomes
}

type OutcomeStats = {
  outcome: Outcome
  median: number
  p95: number
  min: number
  max: number
  parsePass: number
  totalSamples: number
}

function summarize(outcome: Outcome): OutcomeStats {
  const successes = outcome.samples.filter((s) => !s.errorMessage).map((s) => s.ms)
  // Drop first sample as warm-up if we have more than 1
  const measured = outcome.samples.length > 1 ? successes.slice(1) : successes
  const s = measured.length > 0
    ? statsOf(measured)
    : { median: 0, p95: 0, min: 0, max: 0 }
  const parsePass = outcome.samples.filter((s) => s.parseOk).length
  return {
    outcome,
    median: s.median,
    p95: s.p95,
    min: s.min,
    max: s.max,
    parsePass,
    totalSamples: outcome.samples.length,
  }
}

function printTable(results: Outcome[], hasPreFilter: boolean): void {
  type Row = { matcher?: OutcomeStats; 'matcher-prefilter'?: OutcomeStats; drafter?: OutcomeStats }
  const grouped = new Map<BenchBackend, Row>()
  for (const r of results) {
    if (!grouped.has(r.backend)) grouped.set(r.backend, {})
    const stats = summarize(r)
    grouped.get(r.backend)![r.prompt] = stats
  }

  const fmt = (s?: OutcomeStats) => {
    if (!s) return '—'
    if (s.median === 0) return 'ALL FAIL'
    return `${(s.median / 1000).toFixed(2)}s / ${(s.p95 / 1000).toFixed(2)}s`
  }
  const parseStr = (s?: OutcomeStats) => {
    if (!s) return '—'
    if (s.totalSamples === 0) return '—'
    return `${s.parsePass}/${s.totalSamples}`
  }

  console.log('')
  console.log('### Measured latencies — median / p95 over N samples (first sample dropped as warm-up)')
  console.log('')

  if (hasPreFilter) {
    console.log(
      '| Backend     | Matcher (full 50)     | Matcher (pre-filter top-8) | Speedup | Drafter (trilingual)  | Match-full parse | Match-pf parse | Drafter parse |',
    )
    console.log(
      '|-------------|-----------------------|----------------------------|---------|-----------------------|------------------|----------------|---------------|',
    )
    for (const backend of BENCH_BACKENDS) {
      const row = grouped.get(backend)
      if (!row) {
        console.log(`| \`${backend.padEnd(11)}\` | not registered        | not registered             | —       | not registered        | —                | —              | —             |`)
        continue
      }
      const speedup =
        row.matcher && row['matcher-prefilter'] &&
        row.matcher.median > 0 && row['matcher-prefilter'].median > 0
          ? `${(row.matcher.median / row['matcher-prefilter'].median).toFixed(1)}×`
          : '—'
      console.log(
        `| \`${backend.padEnd(11)}\` | ${fmt(row.matcher).padEnd(21)} | ${fmt(row['matcher-prefilter']).padEnd(26)} | ${speedup.padEnd(7)} | ${fmt(row.drafter).padEnd(21)} | ${parseStr(row.matcher).padEnd(16)} | ${parseStr(row['matcher-prefilter']).padEnd(14)} | ${parseStr(row.drafter).padEnd(13)} |`,
      )
    }
  } else {
    console.log('| Backend     | Matcher (median / p95) | Drafter (median / p95) | Matcher parse | Drafter parse |')
    console.log('|-------------|------------------------|------------------------|---------------|---------------|')
    for (const backend of BENCH_BACKENDS) {
      const row = grouped.get(backend)
      if (!row) {
        console.log(`| \`${backend}\` | not registered         | not registered         | —             | —             |`)
        continue
      }
      console.log(
        `| \`${backend.padEnd(11)}\` | ${fmt(row.matcher).padEnd(22)} | ${fmt(row.drafter).padEnd(22)} | ${parseStr(row.matcher).padEnd(13)} | ${parseStr(row.drafter).padEnd(13)} |`,
      )
    }
  }
  console.log('')
  console.log('Each cell: median / p95 over (samples - 1) measurements (first sample is warm-up, dropped).')
  console.log('Parse column: <N successful parses> / <N total samples including warm-up>.')
  if (hasPreFilter) {
    console.log('Pre-filter: embeddings + cosine sim (sentence-transformers, local) narrow 50 → top-8 before the LLM call. Embedding overhead (~50ms per question) is INCLUDED in the timing.')
  }
  console.log('')
  console.log('### Per-backend "warming" check (sample-1 vs last-sample timing)')
  console.log('')
  console.log('| Backend     | Prompt              | Sample 1 | Last sample | Trend  |')
  console.log('|-------------|---------------------|----------|-------------|--------|')
  for (const o of results) {
    if (o.samples.length < 2) continue
    const s1 = o.samples[0]
    const sLast = o.samples[o.samples.length - 1]
    const trend = sLast.ms < s1.ms * 0.85
      ? 'warming'
      : sLast.ms > s1.ms * 1.15
      ? 'cooling'
      : 'flat (cold per call)'
    console.log(
      `| \`${o.backend.padEnd(11)}\` | ${o.prompt.padEnd(19)} | ${(s1.ms / 1000).toFixed(2)}s     | ${(sLast.ms / 1000).toFixed(2)}s      | ${trend} |`,
    )
  }
  console.log('')
  console.log('"flat" = LAPI is spawning a fresh subprocess per call (today\'s behavior). "warming" would suggest something is being reused. See lapi-requirements/02-long-lived-cli-subprocess-sessions.md.')
}

async function main(): Promise<void> {
  console.log('LAPI free-backend bench for DEP\n')
  console.log(`  base URL : ${LAPI_BASE_URL}`)
  console.log(`  token at : ${LAPI_TOKEN_PATH}`)

  // Verify daemon reachable
  try {
    await lapiAdminStatus()
  } catch (err) {
    console.error(
      `\nFATAL: cannot reach LAPI at ${LAPI_BASE_URL}: ${err instanceof Error ? err.message : err}`,
    )
    console.error('Start the daemon with: cd /Volumes/My\\ Book\\ Duo-1/Dev/LAPI && npx tsx src/cli.ts start')
    process.exit(1)
  }

  console.log('  daemon   : reachable ✓\n')

  // Probe which backends are registered
  console.log('Probing registered backends:')
  const registered: BenchBackend[] = []
  for (const b of BENCH_BACKENDS) {
    const ok = await backendIsRegistered(b)
    console.log(`  ${b}${' '.repeat(12 - b.length)} ${ok ? '✓ registered' : '— not registered, will skip'}`)
    if (ok) registered.push(b)
  }
  console.log('')

  if (registered.length === 0) {
    console.error('No free backends registered. Nothing to bench.')
    process.exit(1)
  }

  // Pre-compute the embedding pre-filter once, BEFORE timing the LLM calls.
  // We bake the embedding cost into the matcher-prefilter timing per backend,
  // so this top-level call just primes the worker + warms the model.
  const catalog = buildCatalog()
  let preFilteredCatalog: CatalogEntry[] | null = null
  if (embeddingsAvailable()) {
    console.log('Local embeddings worker available — will measure two-stage matcher too.')
    process.stdout.write('Warming embeddings worker + pre-filtering catalog (one-time) ... ')
    const tWarm = Date.now()
    const visitorQuestion =
      "Combien de temps pour faire renouveler ma carte d'identité ?"
    try {
      preFilteredCatalog = await (async () => {
        const catalogTexts = catalog.map((c) => c.canonical)
        const catalogVectors = await embedTexts(catalogTexts)
        const [questionVector] = await embedTexts([visitorQuestion])
        const scored = catalog.map((c, i) => ({
          c,
          s: cosineSimilarity(questionVector, catalogVectors[i]),
        }))
        scored.sort((a, b) => b.s - a.s)
        console.log(`${((Date.now() - tWarm) / 1000).toFixed(2)}s (embedded ${catalog.length} + 1 question)`)
        console.log(
          `  Top-${PRE_FILTER_TOP_K} by cosine similarity: ${scored
            .slice(0, PRE_FILTER_TOP_K)
            .map((x) => `${x.c.id}(${x.s.toFixed(2)})`)
            .join(', ')}`,
        )
        return scored.slice(0, PRE_FILTER_TOP_K).map((x) => x.c)
      })()
    } catch (err) {
      console.log(`FAILED: ${err instanceof Error ? err.message : err}`)
      console.log('  → continuing without pre-filter measurement')
      preFilteredCatalog = null
    }
  } else {
    console.log('EMBEDDINGS_WORKER_COMMAND unset — will measure only the full-catalog matcher.')
  }

  console.log('')
  console.log('Running benchmark (each backend × matcher full × matcher pre-filter × drafter):\n')
  const allResults: Outcome[] = []

  for (const backend of registered) {
    const outcomes = await benchOne(backend, catalog, preFilteredCatalog)
    allResults.push(...outcomes)
  }

  printTable(allResults, preFilteredCatalog !== null)

  // Persist raw results
  const outPath = resolve(__dirname, 'lapi-bench-results.json')
  writeFileSync(
    outPath,
    JSON.stringify(
      {
        timestamp: new Date().toISOString(),
        baseUrl: LAPI_BASE_URL,
        results: allResults,
      },
      null,
      2,
    ),
  )
  console.log(`Raw results: ${outPath}`)
}

main().catch((err) => {
  console.error('bench failed:', err)
  process.exit(1)
})
